### PR TITLE
WIP - split 3-node mongodb replicaset into seperate template

### PR DESCRIPTION
**Pull request by philbrookes**
Should not be merged until ansible scripts are update to deal with these changes as part of RHMAP-14324

For this to work, the passwords must be generated externally and passed in to both scripts as parameters. For example:
```
oc new-app -f 3-node-mongodb.json -p MONGODB_FHMBAAS_PASSWORD=password -p MONGODB_ADMIN_PASSWORD=password -p MONGODB_FORM_PASSWORD=password -p MONGODB_FHREPORTING_PASSWORD=password
```
```
oc new-app -f fh-mbaas-template-3node.json -p MONGODB_FHMBAAS_PASSWORD=password -p MONGODB_ADMIN_PASSWORD=password -p MONGODB_FORM_PASSWORD=password -p MONGODB_FHREPORTING_PASSWORD=password
```

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
As part of this pr we could remove the MONGODB_FHSTATSD_USER and MONGODB_FHSTATSD_PASSWORD env vars. At the minute they are being set to ${MONGODB_FHSTATSD_PASSWORD} ${MONGODB_FHSTATSD_USER} in the environment section in the mongopods - see [here](https://osm1-master1.feedhenry.net:8443/console/project/3-node-mbaas-430/browse/pods/mongodb-2-4-27pdq)
The user and password values are used for the other pods fh-mbaas, fh-metrics and fh-messaging which are specified in the mongo pod but it would appear these ones aren't

**Comment by laurafitzgerald** [comment]
Also should we consider adding the MONGODB_{component}_USER and MONGODB_{component}_PASSWORD to a config map? That way they could send in the values to the configmap when creating 3-node-mongodb.json and then the fh-mbaas-template-3-node.json would take the values from the config map. Eliminating the possibility of human error.

**Comment by laurafitzgerald** [comment]
@philbrookes just a few comments there. I tried out the config map changes so I can push them up if you'd like to take a look?

**Comment by laurafitzgerald** [comment]
[Here](https://osm1-master1.feedhenry.net:8443/console/project/14321-mbaas/overview) is a link for the mbaas created with the new separate structure.

**Comment by laurafitzgerald** [comment]
hey philbrookes. just looking at this again.
After the new changes the steps i took to do the installation were:
`oc new-app -f 3-node-mongodb.json -p MONGODB_FHMBAAS_PASSWORD=password -p MONGODB_ADMIN_PASSWORD=password -p MONGODB_FORM_PASSWORD=password -p MONGODB_FHREPORTING_PASSWORD=password`
then:
`oc new-app -f fh-mbaas-template-3-node.json` - now gets the value from the config map
and the mbaas came up okay. 
I can mark the JIRA as verified or should there be another verification on my changes?
There would need to be a documentation task also, i'll go ahead and create that.

**Comment by PhilipGough** [comment]
@philbrookes this could potentially be closed in favour of https://github.com/feedhenry/fh-openshift-templates/pull/87 with the long term view of removing the initiator

**Comment by philbrookes** [comment]
@PhilipGough sure thing. I'll close it now.

**Pull request closed without merging**
