### PR TITLE
🚑 Fix scripts for changed template name

### PR DESCRIPTION
**Pull request by grdryn**

### CODE REVIEW

**Comment by grdryn** [comment]
@matskiv If there have been any changes to MBaaS components since you renamed the template file, they may not have been updated here, as the jobs would have failed. E.g. http://bob.feedhenry.net:8080/job/fh-openshift-templates-component-update/2355/console

**Comment by matskiv** [comment]
@grdryn Thanks for noticing this.
I guess I should compare component versions in templates vs last build in components master ? Or will they be updated/rebuilt automatically when we cut 4.4 RC ?

**Comment by grdryn** [comment]
@matskiv I think you may need to check manually. I don't think things get updated as part of the release process yet.

**Comment by matskiv** [comment]
I checked the versions manually, everything in master is ok.

**Comment by grdryn** [comment]
Great, thanks @matskiv!

**Pull request merged**
