### PR TITLE
Remove persistent volume setup

### PR DESCRIPTION
**Pull request by wtrocki**
Removing file because it has no usage for this particular repository. 
File was created at the time when we had all templates together and it somehow managed to be copied to mbaas repos. 
Documentation that refers to this file is in different repository.

Review @david-martin @maleck13 @PhilipGough

### CODE REVIEW

**Comment by PhilipGough** [comment]
I agree with this change. Could I also suggest as part of this cleanup PR to remove https://github.com/feedhenry/fh-openshift-templates#productization-procedure

**Comment by PhilipGough** [comment]
ping @psturc the issue you spotted is going to be done by @wtrocki here since it makes sense in this PR

**Comment by wtrocki** [comment]
Good point! I reviewed README.md and removed some outdated sections.

**Comment by PhilipGough** [comment]
Looks good

**Pull request merged**
